using Term = NOOSE_Website.Infrastructure.Handbook.HandbookContent.SeededTerm;

namespace NOOSE_Website.Infrastructure.Handbook.Content;

/// <summary>The glossary: one sentence per term, plain text, because it ends up inside a tooltip.</summary>
/// <remarks>
/// Terms are deliberately specific rather than short ("Aufgaben-Board", not "Board"): the same list drives the
/// explain-on-hover bubbles across every rich text on the site, and a one-word entry would fire on prose that never
/// meant the term. Legal vocabulary is left out on purpose - it lives in the law book, and a second copy would drift.
/// </remarks>
internal static class GlossaryContent
{
    internal static readonly IReadOnlyList<Term> Terms =
    [
        // --- account, ranks, rights -----------------------------------------
        new("beg-agent", "Agent", "Ein Mitglied der NOOSE mit eigenem Konto auf dieser Seite.",
            ArticleKey: "art-rechte"),
        new("beg-codename", "Codename",
            "Der Name, unter dem dich alle in der Behörde sehen. Nicht dein Klarname.",
            Synonyms: "Deckname", ArticleKey: "art-profil"),
        new("beg-klarname", "Klarname",
            "Der echte Name einer Person. Innerhalb der Behörde sieht ihn nur die Führung.",
            Synonyms: "Realname", ArticleKey: "art-profil"),
        new("beg-dienstgrad", "Dienstgrad",
            "Deine Stufe von Junior Agent bis Director. Entscheidet zusammen mit den Kennzeichen über deine Rechte.",
            Synonyms: "Rang", ArticleKey: "art-rechte"),
        new("beg-fuehrung", "Führung",
            "Alle ab Supervisory Special Agent, dazu Admins. Die Schwelle, ab der Verschlusssachen sichtbar werden.",
            Synonyms: "Leadership", ArticleKey: "art-rechte"),
        new("beg-tru", "TRU",
            "Tactical Response Unit - die taktische Spezialisierung. Ein Kennzeichen am Konto, das es erst ab Special Agent gibt.",
            Synonyms: "Tactical Response Unit", ArticleKey: "art-dvo-abteilungen"),
        new("beg-hrb", "HRB",
            "Human Resource Branch - die Abteilung für Personal und Bewerbungen. Ein Kennzeichen am Konto, das es erst ab Special Agent gibt.",
            Synonyms: "Human Resource Branch, Human Resources Branch", ArticleKey: "art-dvo-abteilungen"),
        new("beg-kennzeichen", "Kennzeichen",
            "Admin, TRU, HRB oder Aufsicht: eine Eigenschaft des Kontos, die neben dem Dienstgrad steht.",
            Synonyms: "Flag", ArticleKey: "art-rechte"),
        new("beg-admin", "Admin",
            "Ein Kennzeichen, das jede Rangprüfung überspringt. Kein Dienstgrad, sondern eine Vollmacht.",
            ArticleKey: "art-rechte"),
        new("beg-aufsicht", "Nur-Lese-Aufsicht",
            "Ein Konto, das alles lesen, aber nichts speichern darf - und nie Klarnamen sieht.",
            Synonyms: "Aufsicht, Teamleitung", ArticleKey: "art-rechte"),
        new("beg-junior-agent", "Junior Agent", "Der erste Dienstgrad. Voller Lesezugriff, eingeschränkte Entscheidungen.",
            ArticleKey: "art-rechte"),
        new("beg-special-agent", "Special Agent", "Der zweite Dienstgrad, die Regelstufe der Ermittlungsarbeit.",
            ArticleKey: "art-rechte"),
        new("beg-senior-special-agent", "Senior Special Agent",
            "Der dritte Dienstgrad. Ab hier darfst du die höchste Einstufung vergeben und selbst veröffentlichen.",
            ArticleKey: "art-rechte"),
        new("beg-supervisory", "Supervisory Special Agent",
            "Der vierte Dienstgrad und der Beginn der Führung.", ArticleKey: "art-rechte"),
        new("beg-deputy-director", "Deputy Director",
            "Der fünfte Dienstgrad. Ab hier werden Beförderungen entschieden.", ArticleKey: "art-befoerderung"),
        new("beg-director", "Director", "Der höchste Dienstgrad der Behörde.", ArticleKey: "art-rechte"),
        new("beg-ausstehend", "Ausstehend",
            "Der Zustand eines frisch angemeldeten Kontos, bevor die Führung es freigibt.",
            ArticleKey: "art-anmelden"),
        new("beg-freigabe-konto", "Kontofreigabe",
            "Die Entscheidung der Führung, ein ausstehendes Konto zu aktivieren und ihm Dienstgrad und Kennzeichen zu geben.",
            ArticleKey: "art-agenten-verwalten"),
        new("beg-einladung", "Einladung",
            "Ein Code, mit dem sich jemand außerhalb des Bewerbungswegs registrieren darf.",
            ArticleKey: "art-agenten-verwalten"),
        new("beg-partner", "Partnerbehörde",
            "LSPD, DoJ oder LSMD. Sieht ausschließlich Akten, die einzeln für sie freigegeben wurden.",
            Synonyms: "Partner", ArticleKey: "art-partner"),
        new("beg-lspd", "LSPD", "Los Santos Police Department - eine Partnerbehörde mit eigenen Konten.",
            ArticleKey: "art-partner"),
        new("beg-doj", "DoJ", "Department of Justice - eine Partnerbehörde mit eigenen Konten.",
            Synonyms: "Department of Justice", ArticleKey: "art-partner"),
        new("beg-lsmd", "LSMD", "Los Santos Medical Department - eine Partnerbehörde mit eigenen Konten.",
            ArticleKey: "art-partner"),
        new("beg-typ-erlaubnis", "Typ-Erlaubnis",
            "Legt fest, welche Aktenarten eine Partnerbehörde überhaupt sehen darf. Schränkt nur ein, gibt nichts frei.",
            ArticleKey: "art-partner"),
        new("beg-einzelfreigabe", "Einzelfreigabe",
            "Gibt eine bestimmte Akte für eine Partnerbehörde frei. Ohne sie zeigt auch eine Typ-Erlaubnis nichts.",
            Synonyms: "Partner-Freigabe", ArticleKey: "art-partner"),
        new("beg-buergerkonto", "Bürgerkonto",
            "Der Zugang, mit dem ein Bürger Hinweise, Tickets und Einsprüche einreicht und Antworten liest.",
            ArticleKey: "art-buergerhinweise"),
        new("beg-zivilidentitaet", "Zivil-Identität",
            "Das Bürgerkonto eines Agenten. Damit kann er als Privatperson etwas einreichen, ohne die Behörde zu nennen.",
            ArticleKey: "art-buergerhinweise"),
        new("beg-bewerber", "Bewerber",
            "Ein Konto im Bewerbungsverfahren: es sieht nur die eigene Bewerbung, keine Akten.",
            ArticleKey: "art-bewerbungen"),

        // --- records --------------------------------------------------------
        new("beg-personenakte", "Personenakte",
            "Die zentrale Akte zu einer Person. Alles, was über sie bekannt ist, läuft dort zusammen.",
            Synonyms: "Personen-Akte", ArticleKey: "art-personenakte"),
        new("beg-personalakte", "Personalakte",
            "Die Akte über einen eigenen Agenten: Dienstgrade, Notizen, Ausbildung, Beförderungen.",
            ArticleKey: "art-personalakte"),
        new("beg-steckbrief", "Steckbrief",
            "Der Abschnitt mit Aliassen, Telefon, Fahrzeugen und Waffen - die Merkmale, nach denen gesucht wird.",
            ArticleKey: "art-steckbrief"),
        new("beg-aktenzeichen", "Aktenzeichen",
            "Die menschenlesbare Nummer einer Akte, etwa NOOSE-P-2026-0001. Wird automatisch vergeben.",
            ArticleKey: "art-aktenzeichen"),
        new("beg-fraktion", "Fraktion",
            "Eine organisierte Gruppe mit Rängen, Mitgliedern und oft eigenem Anwesen.",
            ArticleKey: "art-fraktionen"),
        new("beg-personengruppe", "Personengruppe",
            "Ein loser Zusammenschluss ohne feste Struktur. Die kleinere Schwester der Fraktionsakte.",
            ArticleKey: "art-personengruppen"),
        new("beg-partei", "Partei",
            "Eine politische Organisation mit Mitgliedern und Ausrichtung, getrennt von den Fraktionen geführt.",
            ArticleKey: "art-parteien"),
        new("beg-vorgang", "Vorgang",
            "Die übergeordnete Ermittlungsakte, die mehrere Akten zu einem Fall bündelt.",
            ArticleKey: "art-vorgaenge"),
        new("beg-operation", "Operation",
            "Ein einzelner Einsatz mit Ort, Zeit, Beteiligten und Ergebnis.",
            ArticleKey: "art-operationen"),
        new("beg-taskforce", "Taskforce",
            "Eine genehmigte Einheit mit eigenem Chat. Wer nicht zugeteilt ist, sieht sie gar nicht.",
            ArticleKey: "art-taskforces"),
        new("beg-innerbehoerdlich", "Innerbehördlich",
            "Umfang einer Taskforce: nur NOOSE-Agenten.", ArticleKey: "art-taskforces"),
        new("beg-ueberbehoerdlich", "Überbehördlich",
            "Umfang einer Taskforce: auch Partnerbehörden arbeiten mit.", ArticleKey: "art-taskforces"),
        new("beg-dok", "Dok",
            "Das Protokoll einer Vernehmung oder Maßnahme an einer Person, mit festgehaltenem Ausgang.",
            Synonyms: "Personen-Dok", ArticleKey: "art-doks"),
        new("beg-observation", "Observation",
            "Eine festgehaltene Beobachtung: wer, wann, wo, was gesehen.", ArticleKey: "art-observationen"),
        new("beg-informant", "Informant",
            "Eine Quelle aus dem Milieu, geführt von einem Agenten und mit protokollierten Treffen.",
            Synonyms: "V-Person, V-Mann, Vertrauensperson", ArticleKey: "art-informanten"),
        new("beg-entfuehrung", "Entführung",
            "Der Fall, dass ein NOOSE-Agent entführt wurde - festgehalten wird vor allem, was abgeflossen ist.",
            ArticleKey: "art-entfuehrungen"),
        new("beg-asservat", "Asservat",
            "Ein sichergestellter Gegenstand in der Asservatenkammer, mit Bestand und Besitzer.",
            ArticleKey: "art-asservate"),
        new("beg-asservatenkammer", "Asservatenkammer",
            "Die Buchführung über sichergestellte Gegenstände: Einlagerung, Herausnahme, Bestand.",
            ArticleKey: "art-asservate"),
        new("beg-dokument", "Dokument",
            "Ein Schriftstück in der Bibliothek - Bericht, Vermerk, Anordnung - mit eigener VS-Stufe.",
            ArticleKey: "art-dokumente"),
        new("beg-vorlage", "Vorlage",
            "Ein vorgefertigter Text, dessen Platzhalter beim Einsetzen automatisch gefüllt werden.",
            ArticleKey: "art-dokumente"),
        new("beg-platzhalter", "Platzhalter",
            "Ein Feld in einer Vorlage, das beim Anwenden durch Name, Aktenzeichen, Datum oder Dienstgrad ersetzt wird.",
            ArticleKey: "art-dokumente"),
        new("beg-verknuepfung", "Verknüpfung",
            "Eine Verbindung zwischen zwei Akten. Sie ist immer beidseitig sichtbar.",
            ArticleKey: "art-verknuepfungen"),
        new("beg-quelle", "Quelle",
            "Der Beleg zu einer Angabe: Bild, Datei, Link oder Zitat, angehängt an die Akte.",
            ArticleKey: "art-quellen"),
        new("beg-kommentar", "Kommentar",
            "Die laufende Unterhaltung an einer Akte - der richtige Ort für Einschätzungen statt Tatsachen.",
            ArticleKey: "art-kommentare"),
        new("beg-erwaehnung", "Erwähnung",
            "Ein @ in einem Text, das einen Agenten benachrichtigt oder eine andere Akte verlinkt.",
            Synonyms: "Mention", ArticleKey: "art-kommentare"),
        new("beg-stichwort", "Stichwort",
            "Ein freies Schlagwort an einer Akte, um quer durch den Bestand zu filtern.",
            ArticleKey: "art-stichworte"),
        new("beg-zusatzfeld", "Zusatzfeld",
            "Ein selbst definiertes Feld, das an jeder Akte einer Art erscheint.",
            Synonyms: "Custom-Feld", ArticleKey: "art-stichworte"),
        new("beg-wiedervorlage", "Wiedervorlage",
            "Eine Erinnerung an einer Akte: an diesem Tag soll jemand noch einmal hinsehen.",
            ArticleKey: "art-wiedervorlagen"),
        new("beg-beobachtungsliste", "Beobachtungsliste",
            "Die Akten, denen du folgst. Ändert sich eine, wirst du benachrichtigt.",
            Synonyms: "Beobachtete Akten, Watchlist", ArticleKey: "art-watchlist"),
        new("beg-papierkorb", "Papierkorb",
            "Gelöschte Akten aller Arten. Nichts wird vernichtet, alles lässt sich zurückholen.",
            ArticleKey: "art-papierkorb"),
        new("beg-zeitstrahl", "Zeitstrahl",
            "Der Verlauf einer einzelnen Akte: was wann von wem geändert wurde.",
            Synonyms: "Historie", ArticleKey: "art-nachweis"),
        new("beg-zugehoerigkeit", "Zugehörigkeit",
            "Die Mitgliedschaft einer Person in Fraktion, Partei oder Personengruppe, mit Zeitraum und Rang.",
            ArticleKey: "art-fraktionen"),
        new("beg-beziehung", "Beziehung",
            "Eine benannte Verbindung zwischen zwei Personen - verwandt, verfeindet, geschäftlich.",
            ArticleKey: "art-graph"),
        new("beg-konflikt", "Konflikt",
            "Eine feindliche Beziehung zwischen zwei Fraktionen. Zählt in den Bedrohungs-Score ein.",
            ArticleKey: "art-score"),
        new("beg-buendnis", "Bündnis",
            "Eine verbündete Beziehung zwischen zwei Fraktionen. Zählt in den Bedrohungs-Score ein.",
            ArticleKey: "art-score"),
        new("beg-bestand", "Fraktionsbestand",
            "Was einer Fraktion zugerechnet wird: Waffen, Fahrzeuge, Infrastruktur.",
            Synonyms: "Bestände", ArticleKey: "art-fraktionen"),
        new("beg-fraktionsaktivitaet", "Fraktionsaktivität",
            "Ein festgehaltenes Vorkommnis, an dem eine Fraktion beteiligt war.",
            ArticleKey: "art-fraktionen"),
        new("beg-dienstaktivitaet", "Dienst-Aktivität",
            "Ein Eintrag, den ein Agent über seinen eigenen Dienst führt. Für alle sichtbar.",
            ArticleKey: "art-aktivitaeten"),
        new("beg-lebensstatus", "Lebensstatus",
            "Lebend, tot oder flüchtig. Der Status einer Person in der Akte.",
            ArticleKey: "art-personenakte"),
        new("beg-amnestiespritze", "Amnestie-Spritze",
            "Eine Maßnahme, nach der die Person sich nicht mehr an ihren Kontakt mit der NOOSE erinnert.",
            Synonyms: "Spritze", ArticleKey: "art-doks"),
        new("beg-aktualitaet", "Aktualitäts-Ampel",
            "Grün, gelb oder rot: wie lange niemand mehr in einen Bereich der Fraktionsakte gesehen hat.",
            ArticleKey: "art-aktualitaet"),

        // --- classification and threat --------------------------------------
        new("beg-einstufung", "Einstufung",
            "Wie gefährlich eine Person oder Fraktion gilt: Prüffall, Verdachtsfall oder gesichert staatsgefährdend.",
            ArticleKey: "art-einstufung"),
        new("beg-prueffall", "Prüffall",
            "Die unterste Einstufung: es gibt Anhaltspunkte, mehr nicht.", ArticleKey: "art-einstufung"),
        new("beg-verdachtsfall", "Verdachtsfall",
            "Die mittlere Einstufung: der Verdacht ist belegt genug, um aktiv zu ermitteln.",
            ArticleKey: "art-einstufung"),
        new("beg-staatsgefaehrdend", "Gesichert staatsgefährdend",
            "Die höchste Einstufung. Darf erst ab Senior Special Agent vergeben werden.",
            ArticleKey: "art-einstufung"),
        new("beg-vs", "Verschlusssache",
            "Ein Inhalt, den nur die Führung sieht - oder nur TRU beziehungsweise nur HRB.",
            Synonyms: "VS", ArticleKey: "art-verschlusssachen"),
        new("beg-vs-stufe", "VS-Stufe",
            "Offen, Führung, TRU oder HRB. Sie entscheidet allein, wer ein Dokument sieht.",
            ArticleKey: "art-verschlusssachen"),
        new("beg-score", "Bedrohungs-Score",
            "Eine berechnete Zahl von 0 bis 100 je Person und Fraktion. Sie misst, was dokumentiert ist.",
            Synonyms: "EHK-Score, Score", ArticleKey: "art-score"),
        new("beg-konfidenz", "Konfidenz",
            "Wie gut die Datenlage hinter einem Bedrohungs-Score ist. Niedrig heißt nicht ungefährlich.",
            ArticleKey: "art-score"),
        new("beg-gefaehrdungsstufe", "Gefährdungsstufe",
            "Die Umrechnung des Bedrohungs-Scores in niedrig, mittel, hoch oder kritisch.",
            ArticleKey: "art-score"),
        new("beg-ermittlungshinweis", "Ermittlungshinweis",
            "Eine Auffälligkeit, die das System selbst im Bestand findet. Ein Vorschlag, keine Feststellung.",
            ArticleKey: "art-ermittlungshinweise"),
        new("beg-graph", "Beziehungsgraph",
            "Die Darstellung von Akten als Punkte und ihrer Verbindungen als Linien.",
            Synonyms: "Graph", ArticleKey: "art-graph"),

        // --- wanted and the public side -------------------------------------
        new("beg-ausschreibung", "Öffentliche Ausschreibung",
            "Die Fahndung, wie sie draußen steht. Eine eigene Abschrift der Akte, kein Blick hinein.",
            Synonyms: "Fahndung, Fahndungsausschreibung", ArticleKey: "art-fahndung-anlegen"),
        new("beg-sachfahndung", "Sachfahndung",
            "Eine öffentliche Fahndung nach einem Gegenstand statt nach einer Person.",
            ArticleKey: "art-sachfahndung"),
        new("beg-kopfgeld", "Kopfgeld",
            "Geld auf eine veröffentlichte Fahndung. Nach außen geht nur die Summe, nie wer es gestiftet hat.",
            ArticleKey: "art-kopfgeld"),
        new("beg-belohnung", "Belohnung",
            "Eine Auszahlung an einen Hinweisgeber, dessen Hinweis zur Ergreifung geführt hat.",
            ArticleKey: "art-belohnung"),
        new("beg-buergerhinweis", "Bürgerhinweis",
            "Eine Meldung aus der Bevölkerung, die im internen Hinweis-Eingang landet.",
            Synonyms: "Hinweis", ArticleKey: "art-buergerhinweise"),
        new("beg-anonymitaetszusage", "Anonymitätszusage",
            "Die Zusage, den Namen eines Hinweisgebers nirgends erscheinen zu lassen. Sie ist bindend.",
            ArticleKey: "art-buergerhinweise"),
        new("beg-ergreifungsmeldung", "Ergreifungsmeldung",
            "Ein Bürger meldet, dass er eine gesuchte Person selbst gestellt hat.",
            ArticleKey: "art-ergreifung"),
        new("beg-einspruch", "Einspruch",
            "Der Widerspruch eines Bürgers gegen eine öffentliche Ausschreibung.",
            ArticleKey: "art-einspruch"),
        new("beg-ticket", "Bürger-Ticket",
            "Ein Anliegen eines Bürgers an die Führung, mit Schriftwechsel bis zum Abschluss.",
            Synonyms: "Ticket", ArticleKey: "art-tickets"),
        new("beg-presseerklaerung", "Presseerklärung",
            "Eine redaktionelle Mitteilung der Behörde nach außen, ohne Verfasser.",
            Synonyms: "Presse", ArticleKey: "art-presse"),
        new("beg-warnung", "Öffentliche Warnung",
            "Ein hervorgehobener Hinweis an die Bevölkerung auf eine akute Gefahr, mit Ablaufdatum.",
            ArticleKey: "art-presse"),
        new("beg-gefahrenlage", "Gefahrenlage",
            "Die Ampel auf der öffentlichen Startseite. Von der Führung gesetzt, nicht berechnet.",
            ArticleKey: "art-oeffentliche-lage"),
        new("beg-organisationsprofil", "Organisationsprofil",
            "Die öffentliche Darstellung einer Gruppierung - eine eigene Freigabe, nicht die Fraktionsakte.",
            ArticleKey: "art-oeffentliche-lage"),
        new("beg-modul", "Öffentliches Modul",
            "Ein einzeln abschaltbarer Teil des öffentlichen Bereichs, etwa Fahndung oder Hinweise.",
            ArticleKey: "art-module"),
        new("beg-notaus", "Not-Aus",
            "Ein Schalter, der den gesamten öffentlichen Bereich schließt, ohne einzelne Einstellungen zu ändern.",
            ArticleKey: "art-module"),

        // --- everyday duty --------------------------------------------------
        new("beg-aufgabe", "Aufgabe",
            "Ein To-do der Dienststelle auf dem Aufgaben-Board, mit Zuständigem und Frist.",
            ArticleKey: "art-aufgaben"),
        new("beg-aufgaben-board", "Aufgaben-Board",
            "Die Tafel mit den Spalten Offen, In Arbeit, Erledigt und Verworfen.",
            ArticleKey: "art-aufgaben"),
        new("beg-eingeschraenkt", "Eingeschränkte Aufgabe",
            "Eine Aufgabe, die nur Zugeteilte, der Ersteller und die Führung sehen.",
            ArticleKey: "art-aufgaben"),
        new("beg-termin", "Kalendertermin",
            "Ein Eintrag im Kalender mit Kategorie, Sichtbarkeit und Status.",
            ArticleKey: "art-kalender"),
        new("beg-besprechung", "Besprechung",
            "Eine Dienstbesprechung mit Tagesordnung, Anwesenheit und Protokoll.",
            ArticleKey: "art-besprechungen"),
        new("beg-tagesordnung", "Tagesordnung",
            "Die Punkte, über die in einer Besprechung gesprochen werden soll.",
            ArticleKey: "art-besprechungen"),
        new("beg-besprechungsprotokoll", "Besprechungsprotokoll",
            "Das Ergebnis einer Besprechung. Zwei Stunden nach dem Ende für jeden internen Agenten lesbar.",
            ArticleKey: "art-besprechungen"),
        new("beg-abmeldung", "Abmeldung",
            "Eine angekündigte Abwesenheit. Wer abgemeldet ist, erscheint in Auswahllisten als abwesend.",
            ArticleKey: "art-abmeldungen"),
        new("beg-brett", "Schwarzes Brett",
            "Der Ort für behördliche Ankündigungen, teils mit Pflicht zur Kenntnisnahme.",
            ArticleKey: "art-brett"),
        new("beg-ankuendigung", "Ankündigung",
            "Ein Aushang am Schwarzen Brett, gerichtet an eine bestimmte Gruppe.",
            ArticleKey: "art-brett"),
        new("beg-quittierung", "Kenntnisnahme",
            "Die Bestätigung, dass du eine Ankündigung gelesen hast. Wird als Nachweis gezählt.",
            Synonyms: "Lesebestätigung, Quittierung", ArticleKey: "art-brett"),
        new("beg-bestenliste", "Bestenliste",
            "Das Ranking nach dokumentierter Arbeit. Es misst Dokumentation, nicht Verdienst.",
            ArticleKey: "art-bestenliste"),
        new("beg-benachrichtigung", "Benachrichtigung",
            "Eine Meldung an der Glocke über etwas, das dich persönlich betrifft.",
            ArticleKey: "art-benachrichtigungen"),
        new("beg-schnellsuche", "Schnellsuche",
            "Das Suchfeld, das mit Strg+K auf jeder Seite aufgeht.",
            Synonyms: "Strg+K, Befehlspalette", ArticleKey: "art-suchen"),
        new("beg-lagezentrum", "Lagezentrum",
            "Die Übersichtsseite der Behörde mit den wichtigsten Zahlen und Gefährdungen.",
            Synonyms: "Dashboard", ArticleKey: "art-oberflaeche"),
        new("beg-feedback", "Feedback",
            "Die Meldung an die Betreiber der Seite, wenn etwas fehlt oder nicht funktioniert.",
            ArticleKey: "art-feedback"),

        // --- personnel and money --------------------------------------------
        new("beg-befoerderung", "Beförderung",
            "Der Weg zum nächsten Dienstgrad: Antrag, Entscheidung ab Deputy Director, neue Anmeldung.",
            ArticleKey: "art-befoerderung"),
        new("beg-ausbildungsmodul", "Ausbildungsmodul",
            "Ein Punkt der Einarbeitung, der in der Personalakte einzeln abgehakt wird.",
            ArticleKey: "art-ausbildung"),
        new("beg-bewerbung", "Bewerbung",
            "Der Weg von außen in die Behörde, von der Einreichung bis zur Entscheidung.",
            ArticleKey: "art-bewerbungen"),
        new("beg-sicherheitspruefung", "Sicherheitsüberprüfung",
            "Die Stufe der Bewerbung, in der geprüft wird, ob etwas gegen eine Einstellung spricht.",
            ArticleKey: "art-bewerbungen"),
        new("beg-eignungstest", "Eignungstest",
            "Der Fragebogen im Bewerbungsverfahren. Die Zeit läuft ab dem ersten Abruf der Fragen.",
            Synonyms: "Bewerbungstest", ArticleKey: "art-eignungstest"),
        new("beg-bewerbungssperre", "Bewerbungssperre",
            "Vierzehn Tage Pause nach Ablehnung, Schließung oder nicht bestandener Sicherheitsüberprüfung.",
            Synonyms: "Sperre", ArticleKey: "art-sperren"),
        new("beg-blacklist", "Blacklist",
            "Eine dauerhafte Bewerbungssperre, von Hand gesetzt.", ArticleKey: "art-sperren"),
        new("beg-kasse", "Kasse",
            "Die Buchführung der Behörde über zwei Konten: Schwarzgeld und Grüngeld.",
            ArticleKey: "art-kasse"),
        new("beg-schwarzgeld", "Schwarzgeld",
            "Das Konto für Mittel, die nicht in der offiziellen Buchführung auftauchen.",
            ArticleKey: "art-kasse"),
        new("beg-gruengeld", "Grüngeld",
            "Das Konto für offizielle, belegte Mittel.", ArticleKey: "art-kasse"),
        new("beg-kassenbuchung", "Kassenbuchung",
            "Eine Einzahlung, Auszahlung oder Korrektur. Der Kontostand ergibt sich allein aus den Buchungen.",
            ArticleKey: "art-kasse"),
        new("beg-finanzierung", "Finanzierung",
            "Ein Antrag auf Geld aus der Kasse für Ausrüstung oder einen Einsatz.",
            ArticleKey: "art-finanzierungen"),
        new("beg-monatsbudget", "Monatsbudget",
            "Der Betrag, den ein Agent pro Monat über Finanzierungen abrufen kann.",
            ArticleKey: "art-finanzierungen"),
        new("beg-organigramm", "Organigramm",
            "Der Aufbau der Behörde nach Dienstgrad und Einheit. Nach außen nur einzeln freigegeben.",
            ArticleKey: "art-organigramm"),
        new("beg-kuendigung", "Ausscheiden",
            "Das Beenden eines Kontos. Es verliert jeden Zugriff, bleibt aber in den Protokollen sichtbar.",
            Synonyms: "Kündigung", ArticleKey: "art-ausscheiden"),

        // --- tools ----------------------------------------------------------
        new("beg-noosei", "NOOSEI",
            "Die KI der Behörde. Sie liest genau so viel wie du - und schreibt nie selbst in eine Akte.",
            ArticleKey: "art-noosei"),
        new("beg-kontingent", "Kontingent",
            "Dein wöchentliches Guthaben für NOOSEI-Anfragen. Es füllt sich von selbst wieder auf.",
            ArticleKey: "art-kontingent"),
        new("beg-kurzbrief", "NOOSEI-Kurzbrief",
            "Eine Zusammenfassung einer Akte auf Knopfdruck, mit Quellenangaben.",
            Synonyms: "Kurzbrief", ArticleKey: "art-noosei"),
        new("beg-statistik", "Statistik",
            "Auswertungen über den eigenen Bestand - immer gefiltert auf das, was du sehen darfst.",
            ArticleKey: "art-statistik"),
        new("beg-lagebericht", "Lagebericht",
            "Der monatliche Bericht, den die Seite selbst aus dem Bestand erzeugt.",
            ArticleKey: "art-lageberichte"),
        new("beg-chronik", "Chronik",
            "Der Tagesverlauf der Behörde über alle Akten hinweg.", ArticleKey: "art-nachweis"),
        new("beg-aenderungsprotokoll", "Änderungsprotokoll",
            "Jede Änderung an jeder Akte, mit altem Wert, neuem Wert, Zeitpunkt und Agent.",
            ArticleKey: "art-nachweis"),
        new("beg-zugriffsprotokoll", "Zugriffsprotokoll",
            "Wer welche Akte geöffnet hat.", ArticleKey: "art-nachweis"),
        new("beg-gegenaufklaerung", "Gegenaufklärung",
            "Eigene Regeln dafür, welches Verhalten innerhalb der Seite als auffällig gilt.",
            ArticleKey: "art-gegenaufklaerung"),
        new("beg-gesetzbuch", "Gesetzbuch",
            "Die Sammlung der Paragrafen. Einzelne Auszüge lassen sich für die Öffentlichkeit freigeben.",
            Synonyms: "Gesetze", ArticleKey: "art-gesetze"),
        new("beg-druckansicht", "Druckansicht",
            "Eine Akte ohne Menü und Knöpfe, für Papier oder PDF. Ebenfalls rechtegefiltert.",
            ArticleKey: "art-druck"),
        new("beg-wartungsmodus", "Wartungsmodus",
            "Ein Zustand, in dem alle außer Admins nur einen Hinweis sehen.",
            ArticleKey: "art-einstellungen"),
        new("beg-handbuch", "Handbuch",
            "Diese Anleitung. Führung und HRB können sie bearbeiten.",
            ArticleKey: "art-handbuch-pflegen"),
        new("beg-glossar", "Glossar",
            "Die alphabetische Begriffsliste am Ende des Handbuchs.",
            ArticleKey: "art-handbuch-pflegen"),
        new("beg-neuerungen", "Neuerungen",
            "Die Liste der Änderungen an dieser Seite, nach Fassungen gegliedert.",
            Synonyms: "Changelog", ArticleKey: "art-neuerungen"),
        new("beg-fassung", "Fassung",
            "Ein Stand dieser Seite, unter dem mehrere Änderungen zusammengefasst sind.",
            Synonyms: "Version", ArticleKey: "art-neuerungen"),
        new("beg-buildnummer", "Build-Nummer",
            "Die laufende Nummer des tatsächlich installierten Stands, etwa 1.0.412.",
            ArticleKey: "art-neuerungen"),

        // --- service regulation ---------------------------------------------
        new("beg-dienstverordnung", "Dienstverordnung",
            "Die verbindliche Grundlage des Dienstes. Im Zweifel gilt sie, nicht das Handbuch.",
            Synonyms: "DVO", ArticleKey: "art-dvo-dienstverordnung"),
        new("beg-sicherheitsfreigabe", "Sicherheitsfreigabe",
            "Die Stufe, bis zu der du klassifizierte Informationen einsehen darfst. Nicht dasselbe wie die VS-Stufe auf dieser Seite.",
            Synonyms: "Sicherheitsfreigaben, Freigabestufe", ArticleKey: "art-dvo-freigaben"),
        new("beg-rangprinzip", "Rangprinzip",
            "Die Freigabe, die dein Dienstgrad von selbst mitbringt.",
            ArticleKey: "art-dvo-freigaben"),
        new("beg-fachprinzip", "Fachprinzip",
            "Die Freigabe, die dein Einsatzbereich nötig macht - sie kann eine Stufe situationsbedingt anheben.",
            ArticleKey: "art-dvo-freigaben"),
        new("beg-confidential", "Sicherheitsfreigabe Confidential",
            "Die Grundstufe der Dienstverordnung für interne Informationen, für sämtliche Special Agenten.",
            ArticleKey: "art-dvo-freigaben"),
        new("beg-secret", "Sicherheitsfreigabe Secret",
            "Erweiterte Freigabe für operative Inhalte und Lageberichte; nach dem Rangprinzip beim Supervisory Special Agent.",
            ArticleKey: "art-dvo-freigaben"),
        new("beg-top-secret", "Sicherheitsfreigabe Top Secret",
            "Stufe 5 der Dienstverordnung, dem Director und dem Deputy Director vorbehalten.",
            ArticleKey: "art-dvo-freigaben"),
        new("beg-sap", "Special Access Program",
            "Stufe 6 und keine gewöhnliche Freigabe, sondern eine Zusatzstufe für besonders abgeschirmte Ermittlungen.",
            Synonyms: "SAP", ArticleKey: "art-dvo-freigaben"),
        new("beg-cid", "Criminal Investigative Division",
            "Die Hauptdirektion und die Grundeinheit der Ermittlungsarbeit; hier ist jeder Agent zuhause.",
            Synonyms: "CID", ArticleKey: "art-dvo-abteilungen"),
        new("beg-grundeinweisung", "Grundeinweisung",
            "Die erste Pflichtausbildung; ohne sie beginnt der Regeldienst nicht.",
            ArticleKey: "art-dvo-ausbildungen"),
        new("beg-tarnausbildung", "Tarnausbildung",
            "Die zweite Pflichtausbildung vor dem Regeldienst; sie regelt Tarnung, Legendenbildung und verdecktes Auftreten.",
            ArticleKey: "art-dvo-ausbildungen"),
        new("beg-drohnenausbildung", "Drohnenausbildung",
            "Berechtigt zur Aufklärungsdrohne und ist Voraussetzung für die Beförderung zum Special Agent.",
            ArticleKey: "art-dvo-ausbildungen"),
        new("beg-undercover", "Undercover",
            "Verdeckte Informationsgewinnung im regulären Dienst; jeder ausgebildete Agent darf das.",
            ArticleKey: "art-dvo-regeldienst"),
        new("beg-infiltration", "Infiltration",
            "Das langfristige verdeckte Eindringen in eine Struktur - nur nach interner Genehmigung.",
            ArticleKey: "art-dvo-regeldienst"),
        new("beg-sanktionsstufe", "Sanktionsstufe",
            "Eine der sechs Disziplinarstufen, vom Verweis bis zur Entlassung; jede hat eine eigene Rangschwelle.",
            Synonyms: "Sanktionsstufen, Disziplinarmaßnahme", ArticleKey: "art-dvo-sanktionen"),
        new("beg-verweis", "Negativer Vermerk",
            "Die erste Sanktionsstufe: ein Eintrag in der Personalakte bei geringfügigen oder erstmaligen Verstößen.",
            Synonyms: "Verweis", ArticleKey: "art-dvo-sanktionen"),
        new("beg-weisungsbefugnis", "Weisungsbefugnis",
            "Wer wem dienstlich etwas anordnen darf. In einer Taskforce hat sie die Einsatzleitung, nicht der höchste Dienstgrad.",
            ArticleKey: "art-dvo-weisung"),
        new("beg-parlamentspraesidium", "Parlamentspräsidium",
            "Vorsitz des Bundesrates und Speaker - der Behörde übergeordnet.",
            ArticleKey: "art-dvo-weisung"),
        new("beg-funkcode", "Funkcode",
            "Ein Kürzel im Funkverkehr, etwa 10-1 für die Anmeldung im Funkkreis.",
            Synonyms: "Funkcodes", ArticleKey: "art-dvo-funk"),
        new("beg-funkdisziplin", "Funkdisziplin",
            "Die Regeln für das Sprechen im Funk: klar, knapp, erst wenn der Kanal frei ist.",
            ArticleKey: "art-dvo-funk"),
        new("beg-funkpflicht", "Funkpflicht",
            "Die Pflicht, im Dienst dauerhaft im eigenen Funkkanal erreichbar zu sein.",
            ArticleKey: "art-dvo-funk"),
        new("beg-dienstnummer", "Dienstnummer",
            "Deine interne Kennung als römische Zahl von I bis XXV, vor allem für den Funk.",
            ArticleKey: "art-dvo-funk"),
        new("beg-jailbreak-handy", "Jailbreak-Handy",
            "Das einzige im Dienst zugelassene Kommunikationsgerät.",
            ArticleKey: "art-dvo-funk"),
        new("beg-tarnfahrzeug", "Tarnfahrzeug",
            "Ein Fahrzeug einer anderen Organisation, das nur im Zuge einer Tarnung geführt werden darf.",
            Synonyms: "Tarnfahrzeuge", ArticleKey: "art-dvo-fahrzeuge"),
        new("beg-blacksite", "Blacksite",
            "Geheime Einrichtung für sensible Operationen und die Bearbeitung von Tatverdächtigen.",
            ArticleKey: "art-dvo-gebaeude"),
        new("beg-fraktionskasse", "Fraktionskasse",
            "Die Kasse, aus der dienstlich benötigte Mittel erstattet werden.",
            ArticleKey: "art-dvo-dienstmittel"),
    ];
}
