// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NOOSE_Website.Data;

#nullable disable

namespace NOOSE_Website.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609143153_Phase3b_Verknuepfungen")]
    partial class Phase3b_Verknuepfungen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Codename")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<int?>("Dienstgrad")
                        .HasColumnType("int");

                    b.Property<string>("Dienstnummer")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("DiscordRollenSyncAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiscordUsername")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FreigegebenAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FreigegebenVonId")
                        .HasColumnType("longtext");

                    b.Property<string>("GesperrtGrund")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IstAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IstTRU")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Klarname")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("RegistriertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.AktenzeichenZaehler", b =>
                {
                    b.Property<int>("Jahr")
                        .HasColumnType("int");

                    b.Property<int>("LetzteNummer")
                        .HasColumnType("int");

                    b.HasKey("Jahr");

                    b.ToTable("AktenzeichenZaehler");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.EinstufungVerlauf", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgentId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AgentName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("AntragId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Begruendung")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Wert")
                        .HasColumnType("int");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("EinstufungVerlauf");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Aktenzeichen")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("longtext");

                    b.Property<int>("Einstufung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErstelltVonId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeaendertVonId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GeloeschtAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeloeschtVonId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IstVerschlusssache")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Lebensstatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("TotBis")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Aktenzeichen")
                        .IsUnique();

                    b.HasIndex("IstVerschlusssache");

                    b.HasIndex("Name");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonAlias", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Aliasname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonAliase");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonBeziehung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErstelltVonId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeaendertVonId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GeloeschtAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeloeschtVonId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notiz")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PersonAId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PersonBId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonAId");

                    b.HasIndex("PersonBId");

                    b.ToTable("PersonBeziehungen");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonDok", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Ausgang")
                        .HasColumnType("int");

                    b.Property<string>("ErhalteneInformationen")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErstelltVonId")
                        .HasColumnType("longtext");

                    b.Property<string>("Fraktion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeaendertVonId")
                        .HasColumnType("longtext");

                    b.Property<bool>("GedaechtnisGeloescht")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("GeloeschtAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeloeschtVonId")
                        .HasColumnType("longtext");

                    b.Property<string>("Grund")
                        .HasColumnType("longtext");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Wahrheitsserum")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonDoks");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonFahrzeug", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Kennzeichen")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonFahrzeuge");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonFoto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DateinameGespeichert")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErstelltVonId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("GroesseBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonFotos");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonOrt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notiz")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonOrte");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonTelefon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Bezeichnung")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nummer");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonTelefone");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonWaffe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonWaffen");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Querschnitt.Kommentar", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AutorName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("EntitaetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("EntitaetTyp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErstelltVonId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeaendertVonId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GeloeschtAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeloeschtVonId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EntitaetTyp", "EntitaetId");

                    b.ToTable("Kommentare");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Querschnitt.Quelle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DateinameGespeichert")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("EntitaetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("EntitaetTyp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErstelltVonId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeaendertVonId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GeloeschtAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeloeschtVonId")
                        .HasColumnType("longtext");

                    b.Property<long?>("GroesseBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("ZielId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ZielTyp")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("EntitaetTyp", "EntitaetId");

                    b.ToTable("Quellen");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Querschnitt.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErstelltVonId")
                        .HasColumnType("longtext");

                    b.Property<string>("Farbe")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeaendertVonId")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Querschnitt.TagZuordnung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EntitaetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("EntitaetTyp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EntitaetTyp", "EntitaetId");

                    b.HasIndex("TagId", "EntitaetTyp", "EntitaetId")
                        .IsUnique();

                    b.ToTable("TagZuordnungen");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Querschnitt.Verknuepfung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErstelltVonId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeaendertVonId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GeloeschtAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeloeschtVonId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IstGeloescht")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NachId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NachTyp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("VonId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("VonTyp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("NachTyp", "NachId");

                    b.HasIndex("VonTyp", "VonId");

                    b.ToTable("Verknuepfungen");
                });

            modelBuilder.Entity("NOOSE_Website.Infrastructure.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AenderungenJson")
                        .HasColumnType("longtext");

                    b.Property<string>("AgentId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AgentName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Aktion")
                        .HasColumnType("int");

                    b.Property<string>("EntitaetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("EntitaetTyp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Zeitpunkt");

                    b.HasIndex("EntitaetTyp", "EntitaetId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NOOSE_Website.Infrastructure.Audit.ZugriffsLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AgentName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("EntitaetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("EntitaetTyp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EntitaetTyp", "EntitaetId");

                    b.ToTable("ZugriffsLogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NOOSE_Website.Data.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.EinstufungVerlauf", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Personen.Person", "Person")
                        .WithMany("EinstufungVerlauf")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonAlias", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Personen.Person", "Person")
                        .WithMany("Aliase")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonBeziehung", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Personen.Person", "PersonA")
                        .WithMany()
                        .HasForeignKey("PersonAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NOOSE_Website.Data.Entities.Personen.Person", "PersonB")
                        .WithMany()
                        .HasForeignKey("PersonBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonA");

                    b.Navigation("PersonB");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonDok", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Personen.Person", "Person")
                        .WithMany("Doks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonFahrzeug", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Personen.Person", "Person")
                        .WithMany("Fahrzeuge")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonFoto", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Personen.Person", "Person")
                        .WithMany("Fotos")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonOrt", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Personen.Person", "Person")
                        .WithMany("Orte")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonTelefon", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Personen.Person", "Person")
                        .WithMany("Telefonnummern")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.PersonWaffe", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Personen.Person", "Person")
                        .WithMany("Waffen")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Querschnitt.TagZuordnung", b =>
                {
                    b.HasOne("NOOSE_Website.Data.Entities.Querschnitt.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("NOOSE_Website.Data.Entities.Personen.Person", b =>
                {
                    b.Navigation("Aliase");

                    b.Navigation("Doks");

                    b.Navigation("EinstufungVerlauf");

                    b.Navigation("Fahrzeuge");

                    b.Navigation("Fotos");

                    b.Navigation("Orte");

                    b.Navigation("Telefonnummern");

                    b.Navigation("Waffen");
                });
#pragma warning restore 612, 618
        }
    }
}
